            - name: Vue to Git Branch
  # You may pin to the exact commit or the version.
  # uses: LizAinslie/VueBuildToBranchAction@b1b6b10c9babea68424025ef92d0b0af3e871d67
  uses: LizAinslie/VueBuildToBranchAction@1.0.2+1
  with:
    # Your username
    username: RealCltdj
    # Your reponame
    reponame: website
    # Your Github token
    token: ${{ secrets.GITHUB_TOKEN }}
    # Your git commit email
    gitemail: # optional, default is CI@example.com
    # Your git commit name
    gitname: # optional, default is CI
    # Your git commit message
    gitmsg: # optional, default is deploy
    # Your git branch name
    gitbranch: prod
    # Use yarn to build
    useyarn: # optional
          
