name: Build Vue
on:
  push:
    branches:
    - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build
      - run: ./commit-repo.sh ${{ secrets.GITHUB_TOKEN }}
